name: Check & fix styling

on: [ push ]

jobs:
  fix-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: laravel-pint
        uses: aglipanci/laravel-pint-action@2.3.0
        with:
          preset: laravel

      - name: Install NPM dependencies
        run: npm ci

      - name: Run Blade Formatter
        run: node_modules/.bin/blade-formatter --write resources/**/*.blade.php --sort-tailwindcss-classes --sort-html-attributes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
